export const UPDATE_FILTERED_CHARTS_DATA = 'UPDATE_FILTERED_CHARTS_DATA'
export const UPDATE_CURRENT_CHART = 'UPDATE_CURRENT_CHART'

export const UPDATE_FILTER_CRITERIA = 'UPDATE_FILTER_CRITERIA'
export const UPDATE_ORDERS_EXECUTED_CHART_LOADING = 'UPDATE_ORDERS_EXECUTED_CHART_LOADING'
export const UPDATE_PRODUCTS_SOLD_CHART_LOADING = 'UPDATE_PRODUCTS_SOLD_CHART_LOADING'
