export const UPDATE_ORIGIN = 'UPDATE_ORIGIN';
export const UPDATE_DESTINATION = 'UPDATE_DESTINATION';
export const UPDATE_WAYPOINTS = 'UPDATE_WAYPOINTS';
export const UPDATE_ERROR = 'UPDATE_ERROR';
export const UPDATE_SELECTED_POINT = 'UPDATE_SELECTED_POINT';
export const UPDATE_POLYLINE_POINTS = 'UPDATE_POLYLINE_POINTS';
export const RESET_MAP = 'RESET_MAP';
export const CURRENT_LOCATION = 'CURRENT_LOCATION';
