import LocalizedStrings from 'react-native-localization';

export const labels = new LocalizedStrings({
  'en-IE': {
    ENABLE_TOUCH_ID: 'Enable Touch Id for login.',
    CUSTOMERS: 'Customers',
    ROUTE: 'Route Review',
    SYNC: 'Sync',
    SYNC_OFFLINE: 'Offline',
    SYNC_ONLINE: 'Online',
    SYNC_COMPLETED: 'Sync Completed',
    TAP_TO_GO: 'Tap to go',
    SOMETHING_WENT_WRONG: 'Oops Something went wrong. Please try again later',
    SYNC_ERASE_LOCAL_DATABASE: 'Erase Local Database',
    ERACED_LOCAL_DATABSED_ALERT_MESSAGE:
      'Would you like to Erase Local Database',
    SYNC_OFFLINE_MODE_MESSAGE:
      'Seems App is in Offline mode, to sync you need to switch to Online Mode',
    SYNC_NOW_ALERT_MESSAGE: 'Are you sure to start Data Syncing ?',
    ERASED_SUCCESSFULLY_MESSAGE: 'Data Erased Successfully',
    SYNC_NOW_MESSAGE: 'Sync Now',
    SYNC_INPROGRESS_MESSAGE: 'Data Sync in Progress…',
    SYNC_PENDING_MESSAGE: 'You have pending transaction data to be uploaded',
    SYNC_PENDING_FAILED_MESSAGE:
      'You have some failed and pending transaction to be uploaded. Please do Partial Sync to upload them.',
    SYNC_FAILURE: 'Sync Failure:',
    MESSAGING: 'Messaging',
    PRODUCTS: 'Products',
    PRODUCT_DETAIL: 'Product Detail',
    REPORT: 'Day End Report',
    REPORT_SUMMARY: 'DAILY COLLECTION SUMMARY REPORT',
    SUMMARY: 'Summary',
    INVENTORY: 'Stock/Inventory',
    NEWSTOCKREQUEST: 'New Stock Request',
    PERFORMANCE: 'Performance',
    ADMIN: 'Settings',
    DASHBOARD: 'Dashboard',
    SUBMITTED: 'Submitted',
    APPROVED: 'Approved',
    NEWREQUEST: 'New Request',
    STOCKREQUESTS: 'Stock Requests',
    VANINVENTORY: 'Van Inventory',
    VALIDATESTOCK: 'Validate Stock',
    UOM: 'UOM',
    MAP: 'MAP',
    FROM: 'From',
    To: 'To',
    CONNECTIVITY_STATUS_CHANGE_TITLE: 'Connectivity Mode Change',
    ONLINE_TO_OFFLINE_STATUS_CHANGE_MESSAGE:
      'Would you like to change your Connectivity Mode from Online to Offline? \n (In Offline mode local data stored in device is used.)',
    OFFLINE_TO_ONLINE_STATUS_CHANGE_MESSAGE:
      'Would you like to change your Connectivity Mode from Offline to Online? \n (In Online mode Internet connectivity will be required.)',
    YES: 'Yes',
    NO: 'No',
    FULL_SYNC: 'Full Sync',
    PARTIAL_SYNC: 'Partial Sync',
    AREA: 'Area',
    OUTLET_TYPE: 'Outlet Type',
    NEW_CUSTOMER: 'New Customer',
    NEW_ORDER: 'New Order',
    APPLY: 'Apply',
    CLEAR: 'Clear',
    error_fetch_device_location:
      'Please provide permission to fetch current location',
    invalid_origin_error: 'Invalid origin',
    INFO: 'Info',
    ORDER: 'Order',
    INVOICE: 'Invoice',
    INVOICE_NUMBER: 'Invoice No',
    TOTAL_AMOUNT: 'Total Amount',
    AMOUNT_PAID: 'Amount Paid',
    CASH_PAID: 'Cash Paid',
    DUE_DATE: 'Due Date',
    DUE_AMOUNT: 'Due Amount',
    COLLECT_PAYMENT: 'Collect Payment',
    PAYMENT_COLLECTION: 'Payment Collection',
    PAYMENT_HISTORY: 'Payment History',
    ORDER: 'Order',
    CUSTOMER_ACCOUNT_NAME: 'Customer/Account Name',
    GENERAL_INFO: 'General Info:',
    ACCOUNT_TYPE: 'Account Type',
    SHOP_SIZE: 'Shop Size',
    CLUSTER_PRIORITY: 'Cluster Priority',
    PROMOTION_ACCEPTANCE_RATIO: 'Promotion Acceptance Ratio',
    ADDRESS: 'Address',
    SHIPPING_ADDRESS: 'Shipping Address',
    CONTACT_DETAILS: 'Primary Contact Details:',
    CONTACT_PERSON_NAME: 'First Name',
    POSTION_TITLE: 'Last Name',
    EMAIL: 'Email Address',
    PHONE_NUMBER: 'Phone Number ',
    TERMS: 'Terms:',
    OPEN_ITEMS: 'Open Items(Notes):',
    EDIT: 'Edit',
    SAVE: 'Save',
    ADDRESS_LINE1: 'Apartment/Unit',
    ADDRESS_LINE2: 'Street',
    ADDRESS_LINE3: 'Address line3',
    ADDRESS_CITY: 'City',
    ADDRESS_STATE: 'State',
    ADDRESS_POSTAL_CODE: 'Postal Code',
    ADDRESS_COUNTRY: 'Country',
    ADDRESS_PROVINCE: 'Province',
    ADDRESS_COUNTY: 'County',
    SYS_QTY: 'SYS QTY',
    QTY: 'QTY',
    STOCK_QUANTITY_GREATER: 'System quantity is greater than physical quantity',
    STOCK_QUANTITY_LESSER: 'System quantity is lesser than physical quantity',
    STOCK_QUANTITY_EVEN: 'System quantity is even with physical quantity',
    GOOD: 'Good',
    BAD: 'Bad',
    STOCK_TYPE: 'Stock Type',
    OK: 'OK',
    ERROR: 'Error',
    PROMOTIONS: 'Promotions',
    APPLY_PROMOTIONS: 'Apply Promotions',
    TYPE: 'Type',
    BUDGET_ALLOCATION: 'Budget Allocated',
    PERIOD: 'Valid till',
    PROMOTIONS_APPLIED: 'Selected Promotions Applied',
    NA: 'N/A',
    VIEW: 'View',
    CUSTOMER_TYPE: 'Customer Type',
    CUSTOMER_TYPE_VALUE: 'Cash/Credit',
    PAYMENT_MODE: 'Payment Mode',
    CASH_PAYMENT: 'Cash Payment',
    CASH: 'Cash',
    CHEQUE: 'Cheque',
    E_MONEY: 'E-Money',
    CREDIT_NOTE: 'Credit note',
    PAY_FULL: 'Pay Full',
    ADD: 'Add Payment',
    CHEQUE_DETAILS: 'Cheque Details',
    CHEQUE_AMOUNT: 'Cheque Amount',
    CHEQUE_NO: 'Cheque No',
    CHEQUE_DATE: 'Cheque Date',
    BANK_NAME: 'Bank Name',
    BRANCH_NAME: 'Branch Name',
    E_MONEY_DETAILS: 'E-Money Details',
    AMOUNT: 'Amount',
    DATE: 'Date',
    REMARK: 'Remarks',
    TRANSACTION_ID: 'Transaction/Reference ID',
    CREDIT_NOTES: 'Credit Notes',
    BALANCE: 'Balance',
    STATUS: 'Status',
    MODE: 'Mode',
    FULL_PARTIAL: 'Full/Partial',
    SAVE_PAYMENT: 'Submit',
    PRODUCT_SIZE: 'Size',
    PRODUCT_ELIGIBLITY: 'Eligible For Shipment',
    PRODUCT_COTAINER_ID: 'Container Class Id',
    CATEGORY: 'Category',
    PRODUCT_BRAND: 'Brand',
    PRODUCT_INVENTORY_ID: 'Inventory Id',
    PRODUCT_NAME: 'Name',
    ELIGIBLE_FOR_SALE: 'Eligible For Sale',
    PRODUCT_DEFAULT_UOM: 'Unit Of Measurement',
    PRODCUT_CONTAINER_CLASS: 'Container Class',
    BASE_PRODUCT: 'Base Product',
    F_GROUP: 'F Group',
    DIST_BASE: 'Dist. Base',
    PRICE: 'Price',
    STATUS: 'Status',
    TAX_EXEMPTION: 'Tax Exemption',
    COUNTRY_ORGNAME_BLANK:
      'Organisation Name, Country, Contact Email and Contact Name cannot be left blank.',
    RECORD_SAVE: 'Record has been successfully saved',
    ERROR_ON_ACCOUNT_SAVING:
      'Error while uploading Account data. Please try again.',
    ERROR_ON_CONTACT_SAVING:
      'Error while uploading Contact data. Please try again.',
    GENERATE_ORDER_FROM_PREVIOS_ORDERS: 'Generate order from previous orders',
    SELECT_ITEM_FROM_TEMPLATES: `Select items from product templates's`,
    ADD_PRODUCTS_MANUALLY: 'Add products manually',
    SELECT_ITEM_FROM_TEMPLATES: "Select items from product templates's",
    CANCEL: 'Cancel',
    PREVIOUS_ORDERS: 'PREVIOUS ORDERS',
    NEW_ORDER: 'NEW ORDER',
    PROMOTIONS: 'Promotions',
    TAXATION: 'Taxation',
    INVOICE: 'Invoice',
    GENERATE_REPORT_BUTTON_TITLE: 'Generate Report',
    NO_TRANSACTION_MESSAGE: 'No Transactions Found For Selected Date',
    REPORT_HEADDING_TITLE: 'Payment Details',
    CASH_SALES_TITLE: 'Cash Sales',
    CASH_RETURN_TITLE: 'Cash Return',
    CASH_SALES_NET_TITLE: 'Cash Sales Nett',
    CASH_COLLECTION_TITLE: 'Cash Collection',
    CHEQUE_COLLECTION_TITLE: 'Cheque Collection',
    BANK_TRANSFER_TITLE: 'Bank Transfer',
    CHECK_INTERNET_CONNECTIVITY: 'connectionChange',
    NO_CONNECTIVITY_ERROR: 'NO INTERNET CONNECTION',
    NO_CONNECTIVITY_ERROR_MESSAGE:
      'No Internet connection. Make sure that Wi-Fi or cellular mobile data is turned on, then try again.',
    PRODUCT_TEMPLATE: 'PRODUCT TEMPLATE',
    ORGANISATION_NAME_VALIDATION: 'Organisation name cannot be left blank.',
    CONTACT_PERSON_NAME_VALIDATION: 'Contact Person Name cannot be left blank.',
    ADDRESS_LINE1_VALIDATION: 'Apartment/Unit cannot be left blank.',
    ADDRESS_COUNTRY_VALIDATION: 'Country cannot be left blank.',
    SHOP_SIZE_VALIDATION: 'Shop size can not be left blank',
    EMAIL_VALIDATION: 'Email cannot be left blank.',
    ACCOUNT_TYPE_VALIDATION: 'Account type cannot be left blank.',
    PRODUCT_SEARCH: 'Product code, name or scan barcode',
    PRODUCT_NOT_FOUND: 'Product not Found for scanned code',
    PRODUCT_ADDED:
      'Product already added, you can increase the quantity if needed.',
    ACCOUNT_NOT_CREATED: 'Not able to create the Customer, please try again!',
    CONTACT_NOT_CREATED:
      "Not able to create the Customer's contact, please try again!",
    TODAY: 'Today',
    MTD: 'MTD',
    CALENDAR: 'CALENDAR',
    BAR_CHART_VERTICAL: 'BarChartVertical',
    BAR_CHART_HORIZONTAL: 'BarChartHorizontal',
    HISTOGRAM: 'Histogram',
    PIE_CHART: 'PieChart',
    CHECKIN_CHECKOUT_TIMES: 'Check-in/Check-out Times',
    CASES_PER_HOUR: 'Cases/Hour',
    PRODUCT_TYPES_SOLD: 'Products Sold',
    ORDERS_EXECUTED: 'Orders Executed',
    PRODUCT_APPROVED_SUCCESSFULLY: 'Stock request approved successfully.',
    CHECKIN: 'Check In',
    CHECKOUT: 'Check out',
    COMPLETE: 'Complete',
    ERROR_WHILE_ADDING_PRODUCT: 'Failed to approve stock request.',
    SIGN_IN: 'Sign In',
    FORGOT_PASSWORD: 'Forgot Password',
    USERNAME_EMAIL: 'Username/Email',
    NO_FILTER_SELECTED: 'No filter selected',
    PRODUCT_CODE_NAME: 'Product Code/Name',
    FILTERS: 'Filters',
    DRAFT: 'Draft',
    PROMO_CODE: 'Code',
    PROMO_DETAILS: 'Promo Detail',
    TAXES: 'Taxes',
    DISCOUNT: 'Discount',
    ORDER_ITEMS: 'Order Items',
    PRODUCT_DESCRIPTION: 'Product Description',
    ONLINE_STATUS: 'Online Status',
    TARGET_QUANTITY: 'Target QTY',
    ACHIEVE_QUANTITY: 'Achieve QTY',
    UNIT_PRICE: 'Unit Price',
    TAX: 'Tax',
    TOTAL: 'Total',
    DRAW_YOUR_SIGNATURE: 'Draw Your Signature',
    DONE: 'Done',
    START_DAY: 'Start Day',
    END_DAY: 'End Day',
    ROUTE_COMPLETE: 'Route Completed',
    LOGOUT_MESSAGE:
      'Please confirm if you want to logout from the App, it will clear all data stored locally in the app.',
    CUSTOMER_SIGNATURE: 'Customer Signature',
    INVOICE_DATE: 'Invoice Date',
    SUB_AMOUNT: 'Sub-Amount',
    PRODUCT_TEMPLATE: 'Product Template',
    PRODUCT_TEMPLATE_NOT_FOUND:
      'Product Template not available for the selected Account.',
    PRODUCT_NOT_SELECTED: 'No Product selected, Please select a Product.',
    FULL: 'Full',
    PARTIAL: 'Partial',
    ORDER_SAVE: 'Order Saved Successfully!',
    MAX_INVENTORY_AVAILABLE: 'Maximum Available quantity for this Product is ',
    ORDER_NOT_FOUND: 'Orders not available for the selected Account.',
    ORDER_NOT_SELECTED: 'No order selected, Please select a order.',
    MORE_PRODUCT_ADD_ERROR: 'You reach maximum limit for adding product.',
    ORDER_INVENTORY_NOT_AVAILABLE:
      'Order product quantity is not available in Inventory!',
    ORDER_SUBMITTED: 'Order submitted successfully!',
    CURRENT_ROUTE: 'CURRENT ROUTE',
    CANCELED: 'CANCELED',
    IN_PROGRESS: 'In Progress',
    NOT_STARTED: 'Not Started',
    ON_HOLD: 'On Hold',
    WAITING: 'Waiting',
    REJECTED: 'Rejected',
    SYNC_COMPLETED: 'Sync Completed !',
    SOMETHING_WENT_WRONG: 'Oops something went wrong. Please try again !',
    STOCK_REQUEST_APPROVAL_ALERT:
      "Are you sure you want to submit stock request for approval? You can't edit request once it is approved.",
    VAN_INVENTORY_VALIDATED: 'Van Inventory is validated successfully',
    MORE_PRODUCT_ADD_ERROR: 'You reach max limit for adding product',
    REQUIRED_QUANTITY: 'Required Quantity',
    PRODUCT: 'Product',
    SELECT_PROMOTION: 'Please select a Promotion.',
    ATTACH_IMAGE: 'Attach Image',
    CAPTURE_IMAGE: 'Capture',
    IN_APP_NOTIFICATION_TITLE: 'You are approaching your activity',
    MINIMUM_ORDER_AMOUNT: 'Minimum amount for an order is ',
    IN_APP_NOTIFICATION_MESSAGE: account =>
      `You are around ${account}, want to check in?`,
    PAYMENT_ERROR: 'Enter valid amount to be paid',
    VALIDATE_PROMOTIONS: 'Validate Promotions',
    SUMMARY_PLACEHOLDER: 'Summary Placeholder Screen.',
    ACTIVITY_POST_ERROR: 'Failed to upload activity',
    PRODUCT_POST_ERROR: 'Failed to upload inventory',
    INVENTORY_TRANSACTION_POST_ERROR:
      'Failed to upload route inventory transaction',
    SHOP_SIZE_MANDATORY: 'Shop size is mandatory for wholesaler',
    SELECT_ALL: 'Select All',
    ORDER_BOOKED: 'Booked',
    ORDER_SUBMITTED: 'Submitted',
    ORDER_DELIVERED: 'Delivered',
    ORDER_DRAFT: 'Draft',
    UPLOAD_IMAGE: 'Upload Image',
    MAP_NOT_AVAILABLE: 'Map is not available in offline mode.',
    ERASED_DATABASE_TITLE: 'Erase Database',
    TEMPLATE_SELECTION_ERROR: 'No template selected, Please select a template.'
  },
  'fr-CA': {
    ENABLE_TOUCH_ID: 'Activer Touch Id pour la connexion.',
    CUSTOMERS: 'Les clients',
    ROUTE: "Révision de l'itinéraire",
    SYNC: 'Sync',
    SYNC_OFFLINE: 'Hors ligne',
    SYNC_ONLINE: 'En ligne',
    SYNC_COMPLETED: 'Synchronisation terminée',
    SOMETHING_WENT_WRONG:
      'Oups Une chose s est mal passée. Veuillez réessayer plus tard',
    TAP_TO_GO: 'Appuyez pour aller',
    SYNC_ERASE_LOCAL_DATABASE: 'Effacer la base de données locale',
    ERACED_LOCAL_DATABSED_ALERT_MESSAGE:
      'Voulez-vous effacer la base de données locale',
    SYNC_OFFLINE_MODE_MESSAGE:
      "L'App semble en mode 'Hors-ligne', pour synchroniser vous devez passer en mode 'En ligne'",
    SYNC_NOW_ALERT_MESSAGE:
      'Êtes-vous sûr de vouloir lancer la synchronisation des données?',
    ERASED_SUCCESSFULLY_MESSAGE: 'Données analysées avec succès',
    SYNC_NOW_MESSAGE: 'Synchroniser maintenant',
    SYNC_INPROGRESS_MESSAGE: 'Synchronisation des données en cours…',
    SYNC_PENDING_MESSAGE:
      'Vous avez des données de transaction en attente à télécharger',
    SYNC_PENDING_FAILED_MESSAGE:
      "Vous avez une transaction en échec et en attente à télécharger. S'il vous plaît faire une synchronisation partielle pour les télécharger.",
    SYNC_FAILURE: 'Échec de la synchronisation',
    MESSAGING: 'Messagerie',
    PRODUCTS: 'Produits',
    PRODUCT_DETAIL: 'Détail du produit',
    REPORT: 'Rapport de fin de journée',
    REPORT_SUMMARY: 'RAPPORT SUR LA RECETTE QUOTIDIENNE',
    SUMMARY: 'Résumé',
    INVENTORY: 'Inventaire',
    NEWSTOCKREQUEST: 'Nouvelle demande de stock',
    PERFORMANCE: 'Performance',
    ADMIN: 'Paramètres',
    DASHBOARD: 'Tableau de bord',
    SUBMITTED: 'Soumis',
    APPROVED: 'Approuvé',
    NEWREQUEST: 'Nouvelle requête',
    STOCKREQUESTS: 'Demandes de stock',
    VANINVENTORY: 'Van Inventory',
    VALIDATESTOCK: 'Valider le stock',
    UOM: 'UOM',
    MAP: 'CARTE',
    FROM: 'De',
    To: 'À',
    CONNECTIVITY_STATUS_CHANGE_TITLE: 'Changement de mode de connectivité',
    ONLINE_TO_OFFLINE_STATUS_CHANGE_MESSAGE:
      "Voulez-vous modifier votre mode de connectivité de Online à Offline?  n (En mode hors connexion, les données locales stockées dans l'appareil sont utilisées.)",
    OFFLINE_TO_ONLINE_STATUS_CHANGE_MESSAGE:
      'Souhaitez-vous modifier votre mode de connectivité de Offline à Online?  n (Dans le mode en ligne, la connectivité Internet sera requise.)',
    YES: 'Oui',
    NO: 'Non',
    FULL_SYNC: 'Synchronisation complète',
    PARTIAL_SYNC: 'Synchronisation partielle',
    AREA: 'Région',
    OUTLET_TYPE: 'Type de sortie',
    NEW_CUSTOMER: 'Nouveau client',
    NEW_ORDER: 'Nouvel ordre',
    APPLY: 'Appliquer',
    CLEAR: 'Clair',
    error_fetch_device_location:
      "Veuillez fournir la permission de récupérer l'emplacement actuel",
    invalid_origin_error: 'Origine invalide',
    INFO: 'Info',
    ORDER: 'Ordre',
    INVOICE: "Facture d'achat",
    INVOICE_NUMBER: 'Numéro de facture',
    TOTAL_AMOUNT: 'Montant total',
    AMOUNT_PAID: 'Le montant payé',
    CASH_PAID: 'Payé en espèces',
    DUE_DATE: "Date d'échéance",
    DUE_AMOUNT: 'Montant dû',
    COLLECT_PAYMENT: 'Recueillir le paiement',
    PAYMENT_COLLECTION: 'Collection de paiement',
    PAYMENT_HISTORY: 'historique de paiement',
    CUSTOMER_ACCOUNT_NAME: 'Nom du client/compte',
    GENERAL_INFO: 'Informations générales',
    ACCOUNT_TYPE: 'Type de compte',
    SHOP_SIZE: 'Taille de la boutique',
    CLUSTER_PRIORITY: 'Priorité de cluster',
    PROMOTION_ACCEPTANCE_RATIO: "Ratio d'acceptation de la promotion",
    ADDRESS: 'Adresse',
    SHIPPING_ADDRESS: 'Adresse de livraison',
    CONTACT_DETAILS: 'Détails du contact principal',
    CONTACT_PERSON_NAME: 'Prénom',
    POSTION_TITLE: 'nom de famille',
    EMAIL: 'Adresse e-mail',
    PHONE_NUMBER: 'Numéro de téléphone',
    TERMS: 'termes',
    OPEN_ITEMS: 'Articles ouverts (Notes)',
    EDIT: 'modifier',
    SAVE: 'sauvegarder',
    ADDRESS_LINE1: 'Appartement / Unité',
    ADDRESS_LINE2: 'rue',
    ADDRESS_LINE3: 'Adresse ligne3',
    ADDRESS_CITY: 'Ville',
    ADDRESS_STATE: 'Etat',
    ADDRESS_POSTAL_CODE: 'code postal',
    ADDRESS_COUNTRY: 'Pays',
    ADDRESS_PROVINCE: 'Province',
    ADDRESS_COUNTY: 'Comté',
    SYS_QTY: 'SYS QTY',
    QTY: 'QTÉ',
    STOCK_QUANTITY_GREATER:
      'La quantité de système est supérieure à la quantité physique',
    STOCK_QUANTITY_LESSER:
      'La quantité de système est inférieure à la quantité physique',
    STOCK_QUANTITY_EVEN:
      'La quantité du système est égale à la quantité physique',
    GOOD: 'Bien',
    BAD: 'Mal',
    STOCK_TYPE: 'Type de stock',
    OK: "D'accord",
    ERROR: 'Erreur',
    PROMOTIONS: 'Des promotions',
    APPLY_PROMOTIONS: 'Appliquer les promotions',
    TYPE: 'Type',
    BUDGET_ALLOCATION: 'Budget alloué',
    PERIOD: 'Valid till',
    PROMOTIONS_APPLIED: 'Sélectionnez Promotions appliquées',
    NA: 'N/A',
    VIEW: 'Vue',
    CUSTOMER_TYPE: 'Type de client',
    CUSTOMER_TYPE_VALUE: 'Espèces/Carte de crédit',
    PAYMENT_MODE: 'Mode de paiement',
    CASH_PAYMENT: 'Paiement en espèces',
    CASH: 'En espèces',
    CHEQUE: 'Chèque',
    E_MONEY: 'Monnaie électronique',
    CREDIT_NOTE: 'Note de crédit',
    PAY_FULL: 'Tout payer',
    ADD: 'Ajouter un paiement',
    CHEQUE_DETAILS: 'Détails du chèque',
    CHEQUE_AMOUNT: 'Montant du chèque',
    CHEQUE_NO: 'Numéro de chèque',
    CHEQUE_DATE: 'Date du chèque',
    BANK_NAME: 'Nom de banque',
    BRANCH_NAME: 'Nom de la filiale',
    E_MONEY_DETAILS: 'Détails sur la monnaie électronique',
    AMOUNT: 'Montant',
    DATE: 'Date',
    REMARK: 'Remarques',
    TRANSACTION_ID: 'ID de transition/référence',
    CREDIT_NOTES: 'Notes de crédit',
    BALANCE: 'Équilibre',
    STATUS: 'Statut',
    MODE: 'Mode',
    FULL_PARTIAL: 'Complet / Partiel',
    SAVE_PAYMENT: 'Soumettre',
    PRODUCT_SIZE: 'Taille',
    PRODUCT_ELIGIBLITY: "Eligible à l'expédition",
    PRODUCT_COTAINER_ID: 'ID de classe de conteneur',
    CATEGORY: 'Catégorie',
    PRODUCT_BRAND: 'Marque',
    PRODUCT_INVENTORY_ID: "ID d'inventaire",
    PRODUCT_NAME: 'Nom',
    ELIGIBLE_FOR_SALE: 'Eligible à la vente',
    PRODUCT_DEFAULT_UOM: 'Unité de mesure',
    PRODCUT_CONTAINER_CLASS: 'Classe de conteneur',
    BASE_PRODUCT: 'Produit de base',
    F_GROUP: 'Groupe F',
    DIST_BASE: 'Dist. Base',
    PRICE: 'Prix',
    TAX_EXEMPTION: 'Exonération fiscale',
    COUNTRY_ORGNAME_BLANK:
      "Le nom de l'organisation, le pays, l'adresse électronique du contact et le nom du contact ne peuvent pas être laissés vide.",
    RECORD_SAVE: "L'enregistrement a été enregistré avec succès",
    ERROR_ON_ACCOUNT_SAVING:
      'Erreur lors du téléchargement des données du compte. Veuillez réessayer.',
    ERROR_ON_CONTACT_SAVING:
      'Erreur lors du téléchargement des données de contact. Veuillez réessayer.',
    GENERATE_ORDER_FROM_PREVIOS_ORDERS:
      'Générer une commande à partir de commandes précédentes',
    SELECT_ITEM_FROM_TEMPLATES:
      'Sélectionnez les éléments des modèles de produits',
    ADD_PRODUCTS_MANUALLY: 'Ajouter des produits manuellement',
    CANCEL: 'Annuler',
    PREVIOUS_ORDERS: 'COMMANDES PRÉCÉDENTES',
    TAXATION: 'Imposition',
    GENERATE_REPORT_BUTTON_TITLE: 'Générer un rapport',
    NO_TRANSACTION_MESSAGE:
      'Aucune transaction trouvée pour la date sélectionnée',
    REPORT_HEADDING_TITLE: 'Détails de paiement',
    CASH_SALES_TITLE: 'Les ventes au comptant',
    CASH_RETURN_TITLE: 'Remboursement',
    CASH_SALES_NET_TITLE: 'Cash Sales Nett',
    CASH_COLLECTION_TITLE: 'Paiement en espèces',
    CHEQUE_COLLECTION_TITLE: 'Paiement par chèques',
    BANK_TRANSFER_TITLE: 'Virement',
    CHECK_INTERNET_CONNECTIVITY: 'connectionChange',
    NO_CONNECTIVITY_ERROR: 'PAS DE CONNEXION INTERNET',
    NO_CONNECTIVITY_ERROR_MESSAGE:
      'Pas de connexion Internet. Assurez-vous que les données Wi-Fi ou mobiles sont activées, puis réessayez.',
    PRODUCT_TEMPLATE: 'GABARIT DE PRODUIT',
    ORGANISATION_NAME_VALIDATION:
      "Le nom de l'organisation ne peut pas être laissé vide.",
    CONTACT_PERSON_NAME_VALIDATION: 'Prénom la  ne peut pas être laissé vide.',
    ADDRESS_LINE1_VALIDATION:
      "La ligne d'Appartement / Unité ne peut pas être laissée vide.",
    ADDRESS_COUNTRY_VALIDATION: 'Le pays ne peut pas être laissé vide.',
    SHOP_SIZE_VALIDATION:
      'La taille de la boutique ne peut pas être laissée vide',
    EMAIL_VALIDATION: 'Le courrier électronique ne peut pas être laissé vide.',
    ACCOUNT_TYPE_VALIDATION: 'Le type de compte ne peut pas être laissé vide',
    PRODUCT_SEARCH: 'Code produit, nom ou code-barre',
    PRODUCT_NOT_FOUND: 'Produit non trouvé pour le code scanné',
    PRODUCT_ADDED:
      'Produit déjà ajouté, vous pouvez augmenter la quantité si nécessaire.',
    PRODUCT_NOT_FOUND: 'Product not Found for scanned code',
    ACCOUNT_NOT_CREATED:
      "Impossible de créer le client s'il vous plaît essayez à nouveau!",
    CONTACT_NOT_CREATED:
      'Impossible de créer le contact du client, veuillez réessayer!',
    TODAY: "Aujourd'hui",
    MTD: 'MTD',
    CALENDAR: 'CALENDRIER',
    BAR_CHART_VERTICAL: 'BarChartVertical',
    BAR_CHART_HORIZONTAL: 'BarChartHorizontal',
    HISTOGRAM: 'Histogramme',
    PIE_CHART: 'Camembert',
    CHECKIN_CHECKOUT_TIMES: 'Enregistrement/Check-out Temps',
    CASES_PER_HOUR: 'Paquets / Heures',
    PRODUCT_TYPES_SOLD: 'Produits Vendus',
    ORDERS_EXECUTED: 'Commandes livrées',
    PRODUCT_APPROVED_SUCCESSFULLY: 'Demande de stock approuvée avec succès.',
    CHECKIN: 'Enregistrement',
    CHECKOUT: 'Check-out',
    COMPLETE: 'Achevée',
    ERROR_WHILE_ADDING_PRODUCT: 'Demande de stock refusée',
    SIGN_IN: 'Se connecter',
    FORGOT_PASSWORD: 'Mot de passe oublié',
    USERNAME_EMAIL: "Nom d'utilisateur/adresse e-mail",
    NO_FILTER_SELECTED: 'Aucun filtre sélectionné',
    PRODUCT_CODE_NAME: 'Code produit/Nom',
    FILTERS: 'Des filtres',
    DRAFT: 'Brouillon',
    PROMO_CODE: 'Code',
    PROMO_DETAILS: 'Détail de la promotion',
    TAXES: 'Les taxes',
    DISCOUNT: 'Remise',
    ORDER_ITEMS: 'Items commandés',
    START_DAY: 'Commence jour',
    END_DAY: 'Fin de journée',
    ROUTE_COMPLETE: 'Route terminée',
    LOGOUT_MESSAGE:
      "Souhaitez-vous vraiment vous déconnecter de l'application, cela effacera toutes les données stockées localement dans l'application.",
    PRODUCT_DESCRIPTION: 'Description du produit',
    ONLINE_STATUS: 'Statut de connexion',
    TARGET_QUANTITY: 'Qté cible',
    ACHIEVE_QUANTITY: 'Qté réalisée',
    UNIT_PRICE: 'Prix ​​unitaire',
    TAX: 'Taxe',
    TOTAL: 'Total',
    DRAW_YOUR_SIGNATURE: 'Veuillez Signer ici',
    DONE: 'Terminé',
    START_DAY: 'Date de début',
    END_DAY: 'Date de fin',
    ROUTE_COMPLETE: 'Route terminée',
    CUSTOMER_SIGNATURE: 'Signature du client',
    INVOICE_DATE: 'Date de facture',
    SUB_AMOUNT: 'Sous-montant',
    PRODUCT_TEMPLATE: 'Liste de produits',
    PRODUCT_TEMPLATE_NOT_FOUND:
      'Liste de produits non disponible pour le compte sélectionné.',
    PRODUCT_NOT_SELECTED:
      'Aucun produit sélectionné, veuillez sélectionner un produit.',
    FULL: 'Complet',
    PARTIAL: 'Partiel',
    ORDER_SAVE: 'Commande enregistrée avec succès!',
    MAX_INVENTORY_AVAILABLE:
      'La quantité maximale disponible pour ce produit est ',
    ORDER_NOT_FOUND: 'Commandes non disponibles pour le compte sélectionné.',
    ORDER_NOT_SELECTED:
      'Aucune commande sélectionnée, veuillez sélectionner une commande',
    ORDER_INVENTORY_NOT_AVAILABLE:
      'La quantité de produit de commande n`est pas disponible dans l`inventaire!',
    ORDER_SUBMITTED: 'Commande soumise avec succès!',
    MORE_PRODUCT_ADD_ERROR:
      "Vous atteignez la limite maximale pour l'ajout de produit.",
    CURRENT_ROUTE: 'ROUTE ACTUELLE',
    CANCELED: 'Annulé',
    IN_PROGRESS: 'En cours',
    NOT_STARTED: 'Pas commencé',
    ON_HOLD: 'En attente',
    WAITING: 'Attendre',
    REJECTED: 'Rejeté',
    SYNC_COMPLETED: 'Synchronisation terminée!',
    SOMETHING_WENT_WRONG:
      "Oups, quelque chose s'est mal passé.Veuillez réessayer!",
    STOCK_REQUEST_APPROVAL_ALERT:
      "Voulez-vous vraiment soumettre la demande de stock pour approbation? Vous ne pouvez pas modifier la demande une fois qu'elle est approuvée.",
    VAN_INVENTORY_VALIDATED: 'Van Inventory est validé avec succès',
    REQUIRED_QUANTITY: 'Quantité requise',
    PRODUCT: 'Des produit',
    SELECT_PROMOTION: 'Veuillez sélectionner une promotion.',

    ATTACH_IMAGE: 'Joindre une image',
    CAPTURE_IMAGE: 'Capturer',
    IN_APP_NOTIFICATION_TITLE: 'Vous approchez de votre activité',
    MINIMUM_ORDER_AMOUNT: 'Le montant minimum pour une commande est ',
    IN_APP_NOTIFICATION_MESSAGE: account =>
      `Vous êtes autour de ${account}, vous voulez vous enregistrer?`,
    PAYMENT_ERROR: 'Entrez le montant valide à payer',
    VALIDATE_PROMOTIONS: 'Valider les promotions',
    SUMMARY_PLACEHOLDER: "Écran résumé de l'espace réservé.",
    ACTIVITY_POST_ERROR: "Échec du téléchargement de l'activité",
    PRODUCT_POST_ERROR: "Échec du téléchargement de l'inventaire",
    INVENTORY_TRANSACTION_POST_ERROR:
      "Échec du téléchargement de la transaction d'inventaire de l'itinéraire",
    SHOP_SIZE_MANDATORY:
      'La taille de la boutique est obligatoire pour le grossiste',
    SELECT_ALL: 'tout sélectionner',
    ORDER_BOOKED: 'réservé',
    ORDER_SUBMITTED: 'soumis',
    ORDER_DELIVERED: 'livré',
    ORDER_DRAFT: 'Brouillon',
    UPLOAD_IMAGE: 'télécharger Image',
    MAP_NOT_AVAILABLE: "La carte n'est pas disponible en mode hors connexion.",
    ERASED_DATABASE_TITLE: 'Effacer Base de données',
    TEMPLATE_SELECTION_ERROR:
      'Aucun modèle sélectionné, veuillez sélectionner un modèle.'
  }
});
